// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCHOOL_MANAGEMENT_API.Data;

#nullable disable

namespace SCHOOL_MANAGEMENT_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916183452_data_seeding")]
    partial class data_seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SCHOOL_MANAGEMENT_API.Models.ClassRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Gradelevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ClassRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            Gradelevel = 10,
                            Name = "Grade 10 A"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 25,
                            Gradelevel = 10,
                            Name = "Grade 10 B"
                        });
                });

            modelBuilder.Entity("SCHOOL_MANAGEMENT_API.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Math and Sciences department",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Languages and Literature department",
                            Name = "Languages"
                        });
                });

            modelBuilder.Entity("SCHOOL_MANAGEMENT_API.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 92m,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 85m,
                            StudentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 3,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 78m,
                            StudentId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 90m,
                            StudentId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 5,
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grade = 88m,
                            StudentId = 3,
                            SubjectId = 4
                        });
                });

            modelBuilder.Entity("SCHOOL_MANAGEMENT_API.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassRoomId = 1,
                            DateofBirth = new DateTime(2009, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "karim@student.com",
                            FirstName = "Karim",
                            LastName = "Mostafa",
                            PhoneNumber = "01100000001"
                        },
                        new
                        {
                            Id = 2,
                            ClassRoomId = 1,
                            DateofBirth = new DateTime(2009, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar@student.com",
                            FirstName = "Omar",
                            LastName = "Tarek",
                            PhoneNumber = "01100000002"
                        },
                        new
                        {
                            Id = 3,
                            ClassRoomId = 2,
                            DateofBirth = new DateTime(2010, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laila@student.com",
                            FirstName = "Laila",
                            LastName = "Youssef",
                            PhoneNumber = "01100000003"
                        });
                });

            modelBuilder.Entity("SCHOOL_MANAGEMENT_API.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaxGrade")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Algebra 1",
                            MaxGrade = 100,
                            Name = "Algebra",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Geometry",
                            MaxGrade = 100,
                            Name = "Geometry",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "English Language",
                            MaxGrade = 100,
                            Name = "English",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Physics",
                            MaxGrade = 100,
                            Name = "Physics",
                            TeacherId = 3
                        });
                });

            modelBuilder.Entity("SCHOOL_MANAGEMENT_API.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "ahmed.hassan@school.com",
                            FirstName = "Ahmed",
                            LastName = "Hassan",
                            PhoneNumber = "01000000001",
                            Salary = 15000m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "mona.ali@school.com",
                            FirstName = "Mona",
                            LastName = "Ali",
                            PhoneNumber = "01000000002",
                            Salary = 14000m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Email = "sara.khaled@school.com",
                            FirstName = "Sara",
                            LastName = "Khaled",
                            PhoneNumber = "01000000003",
                            Salary = 16000m
                        });
                });

            modelBuilder.Entity("SCHOOL_MANAGEMENT_API.Models.Enrollment", b =>
                {
                    b.HasOne("SCHOOL_MANAGEMENT_API.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SCHOOL_MANAGEMENT_API.Models.Subject", "Subject")
                        .WithMany("Enrollments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SCHOOL_MANAGEMENT_API.Models.Student", b =>
                {
                    b.HasOne("SCHOOL_MANAGEMENT_API.Models.ClassRoom", "ClassRoom")
                        .WithMany("Students")
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassRoom");
                });

            modelBuilder.Entity("SCHOOL_MANAGEMENT_API.Models.Subject", b =>
                {
                    b.HasOne("SCHOOL_MANAGEMENT_API.Models.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SCHOOL_MANAGEMENT_API.Models.Teacher", b =>
                {
                    b.HasOne("SCHOOL_MANAGEMENT_API.Models.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SCHOOL_MANAGEMENT_API.Models.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SCHOOL_MANAGEMENT_API.Models.Department", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("SCHOOL_MANAGEMENT_API.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SCHOOL_MANAGEMENT_API.Models.Subject", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SCHOOL_MANAGEMENT_API.Models.Teacher", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
